default_context:
  project_name: 'survey'
  project_slug: 'survey'
  domain_main: 'survey.com'
  domain_staging: 'stag.survey.com'
  docker_swarm_stack_name_main: 'survey-com'
  docker_swarm_stack_name_staging: 'stag-survey-com'
  secret_key: 'somethingverydifficult'
  first_superuser: 'admin@survey.com'
  first_superuser_password: 'hello1234'
  backend_cors_origins: '["http://115.186.128.138", "http://115.186.128.138:8080", "http://ec2-18-220-218-41.us-east-2.compute.amazonaws.com","http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.survey.com", "https://stag.survey.com", "https://survey.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@survey.com'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@survey.com'
  pgadmin_default_user_password: 'hello1234'
  traefik_constraint_tag: 'survey.com'
  traefik_constraint_tag_staging: 'stag.survey.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:hello1234'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./