"""add submission no in submission model

Revision ID: 3b47e9746f66
Revises: e0727dd63864
Create Date: 2021-07-16 09:32:52.306512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b47e9746f66'
down_revision = 'e0727dd63864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('submission_no', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'submission_no')
    # ### end Alembic commands ###
