"""update models for submission and surveys

Revision ID: 72caed04d5fa
Revises: 62dc20efb287
Create Date: 2020-12-11 11:14:49.321744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72caed04d5fa'
down_revision = '62dc20efb287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('answers', sa.JSON(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submission_comment'), 'submission', ['comment'], unique=False)
    op.create_index(op.f('ix_submission_id'), 'submission', ['id'], unique=False)
    op.drop_constraint('feedback_owner_id_fkey', 'feedback', type_='foreignkey')
    op.drop_constraint('feedback_survey_id_fkey', 'feedback', type_='foreignkey')
    op.drop_column('feedback', 'owner_id')
    op.drop_column('feedback', 'survey_id')
    op.add_column('hospital', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('hospital', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('hospital', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('survey', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('survey', sa.Column('questions', sa.JSON(), nullable=True))
    op.drop_column('survey', 'answers')
    op.drop_column('survey', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('images', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('survey', sa.Column('answers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('survey', 'questions')
    op.drop_column('survey', 'created_date')
    op.drop_column('hospital', 'lng')
    op.drop_column('hospital', 'lat')
    op.drop_column('hospital', 'created_date')
    op.add_column('feedback', sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedback', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('feedback_survey_id_fkey', 'feedback', 'survey', ['survey_id'], ['id'])
    op.create_foreign_key('feedback_owner_id_fkey', 'feedback', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_submission_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_comment'), table_name='submission')
    op.drop_table('submission')
    # ### end Alembic commands ###
