"""Add column last_name to User model

Revision ID: a02218a47f86
Revises: a6913791047d
Create Date: 2021-06-10 04:51:37.733685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a02218a47f86'
down_revision = 'a6913791047d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('module_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_department_module_name'), 'department', ['module_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_department_module_name'), table_name='department')
    op.drop_column('department', 'module_name')
    # ### end Alembic commands ###
