"""add lazy loading

Revision ID: a043dcb4ae16
Revises: ef395405684f
Create Date: 2020-12-05 15:08:07.930792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a043dcb4ae16'
down_revision = 'ef395405684f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
