"""update users table to include allowed hospitals

Revision ID: a6913791047d
Revises: bc96b4274043
Create Date: 2021-02-25 10:13:57.474335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6913791047d'
down_revision = 'bc96b4274043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('hospital_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_hospital_hospital_type'), 'hospital', ['hospital_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_hospital_type'), table_name='hospital')
    op.drop_column('hospital', 'hospital_type')
    # ### end Alembic commands ###
