"""add meta object in submission model

Revision ID: b7b8ec8316aa
Revises: 3b47e9746f66
Create Date: 2021-07-16 11:37:34.707614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b8ec8316aa'
down_revision = '3b47e9746f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission', 'meta')
    # ### end Alembic commands ###
