"""update users table to include allowed hospitals

Revision ID: bc96b4274043
Revises: 72caed04d5fa
Create Date: 2021-02-08 07:57:32.961869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc96b4274043'
down_revision = '72caed04d5fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('allowed_hospitals', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'allowed_hospitals')
    # ### end Alembic commands ###
