"""remove lazy loading option

Revision ID: be880cdcfc3b
Revises: a043dcb4ae16
Create Date: 2020-12-05 15:34:57.440949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be880cdcfc3b'
down_revision = 'a043dcb4ae16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
