"""add module name in department

Revision ID: e0727dd63864
Revises: a02218a47f86
Create Date: 2021-07-05 08:38:05.855823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0727dd63864'
down_revision = 'a02218a47f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
