"""Add 2 new models for hospital and survey

Revision ID: ef395405684f
Revises: d4867f3a4c0a
Create Date: 2020-12-04 18:32:45.561456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef395405684f'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospital_address'), 'hospital', ['address'], unique=False)
    op.create_index(op.f('ix_hospital_id'), 'hospital', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_name'), 'hospital', ['name'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_index(op.f('ix_survey_name'), 'survey', ['name'], unique=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_survey_name'), table_name='survey')
    op.drop_index(op.f('ix_survey_id'), table_name='survey')
    op.drop_table('survey')
    op.drop_index(op.f('ix_hospital_name'), table_name='hospital')
    op.drop_index(op.f('ix_hospital_id'), table_name='hospital')
    op.drop_index(op.f('ix_hospital_address'), table_name='hospital')
    op.drop_table('hospital')
    # ### end Alembic commands ###
